import {ReactNode} from 'react';
import {Provider} from '@/components/ui/provider';
import styles from './layout.module.scss';
import Header from './components/Header/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={styles.appContainer}>
        <Provider>
          <>
            <Header />
            {children}
          </>
        </Provider>
      </body>
    </html>
  );
}
